import express from "express";
import PDFDocument from "pdfkit";

const router = express.Router();

router.post("/generate", async (req, res) => {
  try {
    const { trip } = req.body;

    if (!trip?.name || !trip?.destination || !trip?.startDate || !trip?.endDate) {
      return res.status(400).json({
        error: "Trip name, destination, startDate, and endDate are required.",
      });
    }

    const filename = `${trip.name.replace(/[^a-z0-9-_]/gi, "_")}_Itinerary.pdf`;

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);

    const doc = new PDFDocument({ margin: 50, size: "A4" });
    doc.pipe(res);

    doc.fontSize(22).text("Travel Buddy - Trip Itinerary", { align: "center" });
    doc.moveDown();
    doc.fontSize(13).text(`Trip Name: ${trip.name}`);
    doc.text(`Destination: ${trip.destination}`);
    doc.text(`Dates: ${trip.startDate} to ${trip.endDate}`);
    doc.moveDown();

    doc.fontSize(16).text("Activities", { underline: true });
    doc.moveDown(0.5);

    if (!trip.activities || trip.activities.length === 0) {
      doc.fontSize(12).text("No activities added.");
    } else {
      trip.activities.forEach((activity, index) => {
        const title = activity.title || "Untitled activity";
        const time = activity.time || "N/A";
        const location = activity.location || "N/A";
        doc
          .fontSize(12)
          .text(`${index + 1}. ${time} - ${title} (${location})`, { indent: 10 });
      });
    }

    doc.moveDown();
    doc.fontSize(10).fillColor("gray").text("Generated by Travel Buddy", {
      align: "right",
    });

    doc.end();
  } catch (error) {
    return res.status(500).json({ error: "Failed to generate PDF." });
  }
});

export default router;
